apiVersion: apps/v1
kind: Deployment
metadata:
    name: aretard
    labels:
        app: aretard
spec:
    replicas: 1
    selector:
        matchLabels:
            app: aretard
    template:
        metadata:
            name: aretard
            labels:
                app: aretard
        spec:
            containers:
                - name: aretard
                  image: arturoguerra/aretard
                  env:
                    - name: PYTHONUNBUFFERED
                      value: "1"
                    - name: LAVALINK_HOST
                      value: lavalink
                    - name: LAVALINK_PORT
                      value: "2333"
                    - name: LAVALINK_URI
                      value: "http://lavalink:2333"
                    - name: LAVALINK_PASSWORD
                      value: "mebigboi"
                    - name: TOKEN
                      valueFrom:
                        secretKeyRef:
                            name: aretard
                            key: token